### PR TITLE
Nest .import files beneath related assets

### PR DESCRIPTION
**Pull request by chornsby**
This PR addresses https://github.com/exigow/intellij-gdscript/issues/49 though not quite in the way that was suggested. I thought I'd open it here to see what you think about this approach instead.

Instead of ignoring the files entirely from the project view, I set default values for the [File Nesting](https://www.jetbrains.com/help/idea/file-nesting-dialog.html) feature. This is usually used for nesting `.css.min` beneath `.css` files and I think the `.*.import` and `.*` files match that use case too.

### Before

current

### After
nested

I'm opening this PR for feedback. This plugin is very cool and I'd like to be able to contribute to it, though I'm not very experienced with Kotlin yet!

TODO:

- [x] Check whether this approach is alright
- [x] Add remaining file extensions to the `EXTENSIONS` array
- [x] Work out how to update list of rules when a new file is added
- [x] Add automated test

### CODE REVIEW

**Comment by exigow** [comment]
Thanks @chornsby, 

the idea of nesting files is brilliant. I think this solves the problem.

```kotlin
fun `test import files are nested by default`() {
    val nestingService = ProjectViewFileNestingService.getInstance()
    val expectedRule = ???
    assertContainsElement(nestingService.rules, expectedRule)
}```

**Comment by exigow** [comment]
Thanks @chornsby, the idea of nesting files is brilliant. I didn't know there was such a feature - I think it fits the problem perfectly.

I have a few questions:

1. Can you please add some tests?

These sources might be useful: https://github.com/JetBrains/intellij-community/blob/a295d3a8a2408cb60870c1ca6739c466f09f4861/java/java-tests/testSrc/com/intellij/projectView/NestedFilesInProjectViewTest.java

My proposal is to add something like:

```kotlin
fun `test import files are nested by default`() {
    // add .png and .import file with same name (environment.addFileToProject)
    // access rules from ProjectViewFileNestingService.getInstance()
    // assertions
}
```

2. Can we use more generic approach instead of extensions list? Like checking if any file has a matching import, regardless of the extension. Proposed whitelist will require constant updates, which I think we want to avoid.

3. I think this multiline comment on top is unnecessary. Your code is clean and self-documented, especially if we provide tests.


> I'm opening this PR for feedback. This plugin is very cool and I'd like to be able to contribute to it, though I'm not very experienced with Kotlin yet!

I'm glad to hear that! :smiley: Regardless of the above comments, I am willing to merge your PR (I'm little busy now - I'll review it tonight). Proposed implementation is a good starting point.

**Comment by chornsby** [comment]
Hi @exigow, thanks very much for the suggestions and the warm welcome. :grin: 

I agree with all of the above and I've just got something rough working to avoid having to maintain a list of known imported extensions. I'll play around with it a bit more tomorrow to see if I can neaten it up and then update this PR. :+1:

**Comment by chornsby** [comment]
I've improved the implementation a little bit by making it totally generic based on the filenames that exist in the project. But this list only updates when the IDE starts (or whenever the `addFileNestingRules` function is called).

I think I need to somehow listen for a signal that a new VFS file has been added and see whether it means we need to add a new rule. Until I get something like that working the test doesn't seem to work, so I'll see if I can make some progress on that. If you have any advice or ideas I'm all ears.

Small steps! :sweat_smile:

**Comment by chornsby** [comment]
I might be slow but I get there in the end!

I've now got a working solution and automated test for the `.import` file nesting. I know that the test is very ugly but it took me a bunch of time last night just getting it to work at all. I found that if I inherited from this project's `BaseTest()` then there was a whole load of unexpected files in the project view which I couldn't explain.

At least now this PR is feature-complete enough for a review. @exigow please do let me know anything else you'd like to see changed and I'll do my best to make it so. 👍

**Comment by exigow** [comment]
Thanks @chornsby! :+1:

**Comment by exigow** [comment]
I tested this `BaseTest()` extension and looks like there is a lot of random files from `/tmp` dir. I have no idea what is causing it, but it's important that your solution works.

(maybe smth with `BaseTest.createTempDir`)

**Comment by exigow** [comment]
@chornsby, FYI I slightly simplified test code in next commit. I hope you don't mind. :P

I replaced inner class with a function that returns an anonymous class. Now you do not have to pass `project` and `testRootDisposable` in every test.

**Comment by chornsby** [comment]
No problem, that looks great! Thanks! :smile:

**Pull request merged**
